apiVersion: v2
name: appflowy
description: Bring projects, wikis, and teams together with AI. AppFlowy is an AI collaborative workspace where you achieve more without losing control of your data. The best open source alternative to Notion. 
home: https://charts.marnas.sh/charts/appflowy/
icon: https://raw.githubusercontent.com/marnas/helm-charts/main/charts/appflowy/icon.png
type: application

# This is the chart version.
version: 0.1.2

# This is the version number of the application being deployed.
# # It is recommended to use it with quotes.
appVersion: "0.7.3"

dependencies:
  - name: common
    version: 3.5.1
    repository: https://bjw-s.github.io/helm-charts/
  - name: gotrue
    version: 0.5.2
    repository: https://small-hack.github.io/gotrue-helm
    condition: gotrue.enabled
  - name: minio
    version: 14.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/AppFlowy-IO/AppFlowy
