{{/* Append the hardcoded settings */}}
{{- define "miniflux.harcodedValues" }}

controllers:
  main:
    containers:
      main:
        env:
          RUN_MIGRATIONS: "1"

          {{- with .Values.ingress.main }}
          {{- if .enabled }}
          BASE_URL: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}/
          {{- end -}}
          {{- end }}

        probes:
          liveness:
            custom: true
            spec:
              httpGet:
                path: /healthcheck
                port: {{ .Values.service.main.ports.http.port }}
{{- end -}}
{{- $_ := merge .Values (include "miniflux.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
